# spisok1 = input()
spisok = "123456"
print(spisok[2])
print(spisok[-2])
print(spisok[:5])
print(spisok[:-2])
print(spisok[1::2])
print(spisok[::2])
print(spisok[::-1])
print(spisok[-2::-2])
print(len(spisok))
